
# siyaram_bookstore/
# ├── settings.py
# ├── urls.py
# ├── celery.py
# ├── asgi.py
# ├── wsgi.py
# └── exceptions.py


# siyaram_bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings
from django.conf.urls.static import static
from django.http import JsonResponse
schema_view = get_schema_view(
    openapi.Info(
        title="Bookstore API",
        default_version="v1",
        description="API documentation for Bookstore project",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/users/", include("users.urls")),
    path("api/books/", include("books.urls")),
    path("api/orders/", include("orders.urls")),

    path("health/", lambda request: JsonResponse({"status": "ok"})),

    # API Docs
    path("swagger/", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

# ⭐ Serve media files (PDF, images, etc.)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	
	
	
	
# siyaram_bookstore/celery.py
import os
from celery import Celery

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "siyaram_bookstore.settings")

app = Celery("siyaram_bookstore")
app.config_from_object("django.conf:settings", namespace="CELERY")
app.autodiscover_tasks()


# siyaram_bookstore/asgi.py

"""
ASGI config for siyaram_bookstore project.

It exposes the ASGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/howto/deployment/asgi/
"""

import os

from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'siyaram_bookstore.settings')

application = get_asgi_application()



# siyaram_bookstore/wsgi.py




"""
WSGI config for siyaram_bookstore project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'siyaram_bookstore.settings')

application = get_wsgi_application()




"""
Django settings for siyaram_bookstore project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

# Installed apps
INSTALLED_APPS = [
    "django.contrib.admin",  # Admin panel
    "django.contrib.auth",  # Authentication system
    "django.contrib.contenttypes",  # Generic relations support
    "django.contrib.sessions",  # Session management
    "django.contrib.messages",  # Flash messages
    "django.contrib.staticfiles",  # Static files handling
    "rest_framework",  # DRF APIs
    "rest_framework_simplejwt",  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # Blacklist support for JWT
    "django_filters",  # Filtering support
    "drf_yasg",  # Swagger docs
    "corsheaders",  # CORS handling (Security)
    "users",  # Custom users app
    "books",  # Books app
    "orders",  # Orders app
]

AUTH_USER_MODEL = "users.User"  # Custom user model
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization: Bearer <access_token>"
        }
    },
    "USE_SESSION_AUTH": False,
}
# DRF configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT auth
    ),
   "DEFAULT_PERMISSION_CLASSES": (
     "rest_framework.permissions.IsAuthenticated",   # Allow login/signup
    ),
    # "DEFAULT_THROTTLE_CLASSES": [
    #     "rest_framework.throttling.UserRateThrottle",  # Auth user limit
    #     "rest_framework.throttling.AnonRateThrottle",  # Anonymous limit
    # ],
    "DEFAULT_THROTTLE_RATES": {"user": "100/day", "anon": "10/day"},  # Throttle rates
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",  # Filter support
        "rest_framework.filters.SearchFilter",  # Search
        "rest_framework.filters.OrderingFilter",  # Ordering
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",  # Custom error handler
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # Pagination
    "PAGE_SIZE": 10,  # Items per page
}

# JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),  # Token expiry
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # Refresh token expiry
    "ROTATE_REFRESH_TOKENS": True,  # Rotate refresh tokens
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Middleware stack
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',  # Security headers
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session middleware
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attach user to request
    'django.contrib.messages.middleware.MessageMiddleware',  # Flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173"
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173"
).split(",")
# Optional: allow all during dev
CORS_ALLOW_ALL_ORIGINS = False
# Cache config using Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Celery configuration
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ['json']  # Accept JSON
CELERY_TASK_SERIALIZER = 'json'  # Task serializer
CELERY_RESULT_SERIALIZER = 'json'  # Result serializer
CELERY_TIMEZONE = 'Asia/Kolkata'  # Timezone

# RAZORPAY_KEY = os.getenv("RAZORPAY_KEY")
# RAZORPAY_SECRET = os.getenv("RAZORPAY_SECRET")
# RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET")

# Logging configuration
# LOGGING = {
#     'version': 1,  # Logging schema version
#     'disable_existing_loggers': False,  # Keep default loggers
#     'formatters': {'verbose': {'format': '[{levelname}] {asctime} {name} {message}', 'style': '{'}},  # Verbose format
#     'handlers': {'file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': BASE_DIR / 'bookstore.log', 'formatter': 'verbose'}},  # File handler
#     'loggers': {
#         'django': {'handlers': ['file'], 'level': 'INFO', 'propagate': True},  # Django logger
#         'orders': {'handlers': ['file'], 'level': 'INFO', 'propagate': False},  # Orders logger
#     },
# }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ROOT_URLCONF = 'siyaram_bookstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siyaram_bookstore.wsgi.application'
ASGI_APPLICATION = 'siyaram_bookstore.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

settings.py








"""
Django settings for siyaram_bookstore project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

# Installed apps
INSTALLED_APPS = [
    "django.contrib.admin",  # Admin panel
    "django.contrib.auth",  # Authentication system
    "django.contrib.contenttypes",  # Generic relations support
    "django.contrib.sessions",  # Session management
    "django.contrib.messages",  # Flash messages
    "django.contrib.staticfiles",  # Static files handling
    "rest_framework",  # DRF APIs
    "rest_framework_simplejwt",  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # Blacklist support for JWT
    "django_filters",  # Filtering support
    "drf_yasg",  # Swagger docs
    "corsheaders",  # CORS handling (Security)
    "users",  # Custom users app
    "books",  # Books app
    "orders",  # Orders app
]

AUTH_USER_MODEL = "users.User"  # Custom user model
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization: Bearer <access_token>"
        }
    },
    "USE_SESSION_AUTH": False,
}
# DRF configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT auth
    ),
   "DEFAULT_PERMISSION_CLASSES": (
     "rest_framework.permissions.IsAuthenticated",   # Allow login/signup
    ),
    # "DEFAULT_THROTTLE_CLASSES": [
    #     "rest_framework.throttling.UserRateThrottle",  # Auth user limit
    #     "rest_framework.throttling.AnonRateThrottle",  # Anonymous limit
    # ],
    "DEFAULT_THROTTLE_RATES": {"user": "100/day", "anon": "10/day"},  # Throttle rates
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",  # Filter support
        "rest_framework.filters.SearchFilter",  # Search
        "rest_framework.filters.OrderingFilter",  # Ordering
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",  # Custom error handler
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # Pagination
    "PAGE_SIZE": 10,  # Items per page
}

# JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),  # Token expiry
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # Refresh token expiry
    "ROTATE_REFRESH_TOKENS": True,  # Rotate refresh tokens
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Middleware stack
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',  # Security headers
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session middleware
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attach user to request
    'django.contrib.messages.middleware.MessageMiddleware',  # Flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173"
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173"
).split(",")
# Optional: allow all during dev
CORS_ALLOW_ALL_ORIGINS = False
# Cache config using Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# Celery configuration
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_ACCEPT_CONTENT = ['json']  # Accept JSON
CELERY_TASK_SERIALIZER = 'json'  # Task serializer
CELERY_RESULT_SERIALIZER = 'json'  # Result serializer
CELERY_TIMEZONE = 'Asia/Kolkata'  # Timezone

# RAZORPAY_KEY = os.getenv("RAZORPAY_KEY")
# RAZORPAY_SECRET = os.getenv("RAZORPAY_SECRET")
# RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET")

# Logging configuration
# LOGGING = {
#     'version': 1,  # Logging schema version
#     'disable_existing_loggers': False,  # Keep default loggers
#     'formatters': {'verbose': {'format': '[{levelname}] {asctime} {name} {message}', 'style': '{'}},  # Verbose format
#     'handlers': {'file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': BASE_DIR / 'bookstore.log', 'formatter': 'verbose'}},  # File handler
#     'loggers': {
#         'django': {'handlers': ['file'], 'level': 'INFO', 'propagate': True},  # Django logger
#         'orders': {'handlers': ['file'], 'level': 'INFO', 'propagate': False},  # Orders logger
#     },
# }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ROOT_URLCONF = 'siyaram_bookstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siyaram_bookstore.wsgi.application'
ASGI_APPLICATION = 'siyaram_bookstore.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

===============================================
# 2.user app

# │   ├── users/ # Authentication, profile, permission, and user-related APIs
# │   │   ├── migrations/ # Database migrations for the users app
# │   │   ├── __init__.py # Marks the users app as a Python package
# │   │   ├── admin.py # Django admin configuration for user models
# │   │   ├── apps.py # App configuration for the users module
# │   │   ├── models.py # User-related database models and relationships
# │   │   ├── permissions.py # Custom permission classes for access control
# │   │   ├── serializers.py # DRF serializers for user data handling
# │   │   ├── services.py # Business logic for user operations
# │   │   ├── views.py # API views for user endpoints
# │   │   ├── urls.py # URL routes for the users app
# │   │   └── tests.py # Unit and integration tests for the users app
# │   │


# users/admin.py
from django.contrib import admin
from django.contrib.auth import get_user_model
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from .models import UserEvent

User = get_user_model()


@admin.register(User)
class UserAdmin(BaseUserAdmin):
    model = User

    list_display = ("mobile", "email", "is_staff", "is_superuser", "is_active","created_at", "updated_at")
    list_filter = ("is_staff", "is_superuser", "is_active")

    search_fields = ("mobile", "email")
    ordering = ("mobile",)
    readonly_fields = ("created_at", "updated_at", "last_login")  
    # IMPORTANT: remove username completely
    fieldsets = (
    (None, {"fields": ("mobile", "password")}),
    ("Personal Info", {"fields": ("email", "first_name", "last_name")}),
    ("Permissions", {"fields": ("is_active", "is_staff", "is_superuser", "groups", "user_permissions")}),
    ("Important dates", {"fields": ("last_login", "created_at", "updated_at")}),  # ✅ FIXED
)

    add_fieldsets = (
        (None, {
            "classes": ("wide",),
            "fields": ("mobile", "password1", "password2", "is_staff", "is_superuser"),
        }),
    )
print("ADMIN LOADED")
@admin.register(UserEvent)
class UserEventAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "event_type", "timestamp")  
    # ✅ UPDATED: better visibility

    list_filter = ("event_type", "timestamp")

    search_fields = ("user__mobile",)

    readonly_fields = ("timestamp",)  




# users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models


class UserManager(BaseUserManager):

    def create_user(self, mobile, password=None, **extra_fields):
        if not mobile:
            raise ValueError("Mobile is required")

        user = self.model(
            mobile=mobile,
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, mobile, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True")

        return self.create_user(mobile, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    mobile = models.CharField(max_length=15, unique=True)

    email = models.EmailField(null=True, blank=True)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)   # ✅ ADDED
    updated_at = models.DateTimeField(auto_now=True, null=True)   
    objects = UserManager()

    USERNAME_FIELD = "mobile"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.mobile


class UserEvent(models.Model):
    EVENT_CHOICES = (
        ("login", "Login"),
        ("signup", "Signup"),
        ("view_book", "View Book"),
        ("purchase", "Purchase"),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event_type = models.CharField(max_length=20, choices=EVENT_CHOICES)

    timestamp = models.DateTimeField(auto_now_add=True)

    # future analytics ready
    metadata = models.JSONField(null=True, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.mobile} - {self.event_type}"
		
		
		
# users/permissions.py
from rest_framework import permissions

class IsOwnerOrReadOnly(permissions.BasePermission):
    """
    Only allow owners to edit their objects.
    """
    def has_object_permission(self, request, view, obj):
        return obj == request.user

class IsAdminUserOrReadOnly(permissions.BasePermission):
    """
    Allow admin users to edit, others can only read.
    """
    def has_permission(self, request, view):
        if request.method in permissions.SAFE_METHODS:  # GET, HEAD, OPTIONS
            return True
        return request.user and request.user.is_staff
		
		
#  users/serializers.py
from rest_framework import serializers
from django.contrib.auth import get_user_model

User = get_user_model()


class UserProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = ("id", "mobile", "email", "first_name", "last_name", "is_staff")
		
		
# users/services.py
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password
from rest_framework.exceptions import ValidationError
from rest_framework_simplejwt.tokens import RefreshToken
from .models import UserEvent

User = get_user_model()


def login_or_register_user(mobile, password):
    mobile = mobile.strip()

    # =========================
    # 1. GET OR CREATE USER
    # =========================
    user = User.objects.filter(mobile=mobile).first()

    # =========================
    # 2. AUTO REGISTER IF NOT EXISTS
    # =========================
    if not user:
        user = User.objects.create_user(
            mobile=mobile,
            password=password,   # IMPORTANT (Django internal)
        )
        user.set_password(password)
        user.save()

        UserEvent.objects.create(user=user, event_type="signup")

    else:
        # =========================
        # 3. VERIFY PASSWORD
        # =========================
        if not user.check_password(password):
            raise ValidationError({"password": "Invalid credentials"})

        UserEvent.objects.create(user=user, event_type="login")

    # =========================
    # 4. GENERATE TOKENS
    # =========================
    refresh = RefreshToken.for_user(user)

    return {
        "access": str(refresh.access_token),
        "refresh": str(refresh),
        "user": {
            "id": user.id,
            "mobile": user.mobile,
            "is_staff": user.is_staff,
        },
    }
	
	
# users/tests.py
from django.test import TestCase

# Create your tests here.



# users/views.py
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.generics import RetrieveUpdateAPIView
from rest_framework_simplejwt.tokens import RefreshToken
from core.responses import success_response, error_response
from .services import User, login_or_register_user
from django.contrib.auth.password_validation import validate_password
from .serializers import UserProfileSerializer


class LoginView(APIView):
    permission_classes = [AllowAny]

    def post(self, request):
        mobile = request.data.get("mobile")
        password = request.data.get("password")

        if not mobile or not password:
            return error_response(
                message="Mobile and password required",
                status_code=400,
            )

        try:
            data = login_or_register_user(mobile, password)
            return success_response("Login successful", data)

        except Exception as e:
            return error_response(
                message="Authentication failed",
                errors=str(e),
                status_code=400,
            )

class LogoutView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        refresh_token = request.data.get("refresh")

        if refresh_token:
            try:
                RefreshToken(refresh_token).blacklist()
            except Exception:
                pass  # 🔥 ignore invalid/expired token

        # ✅ ALWAYS SUCCESS
        return success_response("Logout successful")

class SimpleResetPasswordView(APIView):
    permission_classes = []

    def post(self, request):
        mobile = request.data.get("mobile")
        new_password = request.data.get("password")

        if not mobile or not new_password:
            return error_response("Mobile and password required")

        try:
            user = User.objects.get(mobile=mobile)
        except User.DoesNotExist:
            return error_response("User not found")

        # validate password strength
        validate_password(new_password, user)

        # overwrite password
        user.set_password(new_password)
        user.save()

        return success_response("Password updated successfully")


class ProfileView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        serializer = UserProfileSerializer(request.user)
        return success_response(
            message="Profile fetched",
            data=serializer.data
        )

    def patch(self, request):
        serializer = UserProfileSerializer(
            request.user,
            data=request.data,
            partial=True
        )

        if serializer.is_valid():
            serializer.save()
            return success_response(
                message="Profile updated successfully",
                data=serializer.data
            )

        return error_response(
            message="Validation failed",
            errors=serializer.errors,
            status_code=400
        )
		
		
from django.urls import path
from .views import LoginView, LogoutView, ProfileView, SimpleResetPasswordView
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("reset-password/", SimpleResetPasswordView.as_view()),
    path("profile/", ProfileView.as_view(), name="profile"),
]



# 3.
# books/models.py
# books/serializers.py
# books/views.py
# books/permissions.py
# books/urls.py

# books/admin.py
from django.contrib import admin
from .models import Book, Category


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ("id", "name", "created_at", "updated_at")  
    # ✅ UPDATED: add timestamps (important for analytics tracking)

    search_fields = ("name",)
    ordering = ("name",)

    readonly_fields = ("created_at", "updated_at")  
    # ✅ UPDATED


@admin.register(Book)
class BookAdmin(admin.ModelAdmin):
    list_display = ("id", "title", "author", "price", "category", "created_at", "updated_at")  
    # ✅ UPDATED: added updated_at

    list_filter = ("category", "created_at")
    search_fields = ("title", "author")
    ordering = ("-created_at",)

    autocomplete_fields = ("category",)

    readonly_fields = ("created_at", "updated_at")  # already correct ✅
	
	
	
# books/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    order = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        ordering = ['order']

class Book(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    author = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, related_name="books")
    description = models.TextField(blank=True)
    file = models.FileField(upload_to="books/files/", null=True, blank=True)  # PDF
    cover = models.ImageField(upload_to="books/covers/", null=True, blank=True)  # Cover Image
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=["title", "author"]),
        ]
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.title} by {self.author}"
		
		
# books/serializers.py
from rest_framework import serializers
from .models import Book, Category

class CategorySerializer(serializers.ModelSerializer):
    class Meta:
        model = Category
        fields = ["id", "name"]

class BookSerializer(serializers.ModelSerializer):
    category = CategorySerializer(read_only=True)
    category_id = serializers.PrimaryKeyRelatedField(
        queryset=Category.objects.all(), source="category", write_only=True, required=False
    )

    class Meta:
        model = Book
        fields = '__all__'

    def validate_price(self, value):
        if value <= 0:
            raise serializers.ValidationError("Price must be greater than 0")
        return value

    def validate_title(self, value):
        if not value.strip():
            raise serializers.ValidationError("Title cannot be empty")
        return value

    def validate_author(self, value):
        if not value.strip():
            raise serializers.ValidationError("Author cannot be empty")
        return value
    def validate_file(self, value):
        if value:
            if not value.name.endswith(".pdf"):
                raise serializers.ValidationError("Only PDF files are allowed")
        return value


    def validate_cover(self, value):
        if value:
            if not value.content_type.startswith("image"):
                raise serializers.ValidationError("Invalid image file")
        return value
		
		



# books/views.py
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet
from django.core.cache import cache
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.pagination import PageNumberPagination
import logging

from core.responses import success_response
from users.models import UserEvent

from .models import Book, Category
from .serializers import BookSerializer, CategorySerializer
from .permissions import IsAdminUserOrReadOnly

logger = logging.getLogger(__name__)


# =========================
# PAGINATION
# =========================
class BookPagination(PageNumberPagination):
    page_size = 10


# =========================
# CATEGORY VIEWSET
# =========================
class CategoryViewSet(ReadOnlyModelViewSet):
    queryset = Category.objects.filter(is_active=True)
    serializer_class = CategorySerializer


# =========================
# BOOK VIEWSET
# =========================
class BookViewSet(ModelViewSet):
    queryset = Book.objects.filter(
        is_active=True,
        category__is_active=True   # ✅ IMPORTANT FIX
    ).select_related('category').order_by(
        'category__order', '-created_at'   # ✅ stable + sorted
    )

    serializer_class = BookSerializer
    permission_classes = [IsAdminUserOrReadOnly]

    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter
    ]

    filterset_fields = ["author", "price", "category"]
    search_fields = ["title", "author"]
    ordering_fields = ["price", "created_at", "updated_at"]

    pagination_class = BookPagination

    # =========================
    # LIST (WITH CACHE)
    # =========================
    def list(self, request, *args, **kwargs):
        cache_key = f"books_list_{request.get_full_path()}"
        cached = cache.get(cache_key)

        if cached:
            logger.info("Books served from cache")
            return success_response("Books fetched", cached)

        response = super().list(request, *args, **kwargs)

        cache.set(cache_key, response.data, timeout=60 * 3)

        return success_response("Books fetched", response.data)

    # =========================
    # RETRIEVE
    # =========================
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()

        # Track user event
        if request.user.is_authenticated:
            UserEvent.objects.create(
                user=request.user,
                event_type="view_book"
            )

        serializer = self.get_serializer(instance)
        return success_response("Book details", serializer.data)

    # =========================
    # CREATE
    # =========================
    def perform_create(self, serializer):
        serializer.save()
        cache.clear()
        logger.info(f"{self.request.user} created a book")

    # =========================
    # UPDATE
    # =========================
    def perform_update(self, serializer):
        serializer.save()
        cache.clear()

    # =========================
    # DELETE
    # =========================
    def perform_destroy(self, instance):
        instance.delete()
        cache.clear()
		
# books/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import BookViewSet, CategoryViewSet

router = DefaultRouter()
router.register(r"books", BookViewSet, basename="books")
router.register(r'categories', CategoryViewSet, basename='categories')

urlpatterns = [
    path("", include(router.urls)),

]



# 4.order app


# orders/admin.py
from django.contrib import admin
from .models import Order, OrderItem, Payment


class OrderItemInline(admin.TabularInline):
    model = OrderItem
    extra = 0
    readonly_fields = ("product", "quantity", "price")
    can_delete = False


@admin.register(Order)
class OrderAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "total_amount", "status", "created_at", "updated_at")  
    # ✅ UPDATED: added updated_at

    list_filter = ("status", "created_at")
    search_fields = ("user__mobile", "email", "buyer_name")  
    # ✅ UPDATED: username → mobile (your system uses mobile)

    readonly_fields = ("created_at", "updated_at")  
    # ✅ UPDATED: timestamps should not be editable

    inlines = [OrderItemInline]

    def get_queryset(self, request):
        return super().get_queryset(request).select_related("user")


@admin.register(Payment)
class PaymentAdmin(admin.ModelAdmin):
    list_display = ("id", "order", "payment_id", "paid", "created_at", "updated_at")  
    # ✅ UPDATED: added updated_at

    search_fields = ("payment_id",)
    list_filter = ("paid", "created_at")

    readonly_fields = ("created_at", "updated_at")  
    # ✅ UPDATED

    def get_queryset(self, request):
        return super().get_queryset(request).select_related("order")
		
		
apps.py
from django.apps import AppConfig


class OrdersConfig(AppConfig):
    name = 'orders'




# orders/concurrency.py
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor  # Concurrency modules

def process_order(order_id):  # Task function
    print(f"Processing {order_id}")

def run_threading(order_ids):
    with ThreadPoolExecutor(max_workers=5) as executor:  # Multithreading (IO-bound)
        executor.map(process_order, order_ids)

def run_multiprocessing(order_ids):
    with ProcessPoolExecutor(max_workers=2) as executor:  # Multiprocessing (CPU-bound)
        executor.map(process_order, order_ids)
		
		
# orders/models.py
from django.db import models
from django.conf import settings


class Order(models.Model):
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('SUCCESS', 'Success'),
        ('FAILED', 'Failed')
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="orders"
    )

    total_amount = models.DecimalField(max_digits=10, decimal_places=2,default=0)  # ✅ FIXED

    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='PENDING'
    )

    buyer_name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    invoice_pdf = models.FileField(
        upload_to="invoices/",
        null=True,
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)  

    def __str__(self):
        return f"Order #{self.id}"
    

class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        related_name="items",
        on_delete=models.CASCADE
    )

    product = models.ForeignKey(
        'books.Book',
        on_delete=models.CASCADE
    )

    quantity = models.PositiveIntegerField(default=1)  # ✅ safer
    price = models.DecimalField(max_digits=10, decimal_places=2)  # ✅ FIXED

    class Meta:
        unique_together = ('order', 'product')

class Payment(models.Model):
    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE,
        related_name="payment"
    )

    payment_id = models.CharField(max_length=200, null=True, blank=True)

    paid = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
	
	
# orders/permissions.py
from rest_framework.permissions import BasePermission

class IsAdminOrOwner(BasePermission):  # RBAC (Authorization)
    def has_object_permission(self, request, view, obj):
        return request.user.is_staff or obj.user == request.user
		
		
# orders/serializers.py

from rest_framework import serializers
from .models import Order, OrderItem, Payment


class OrderItemSerializer(serializers.ModelSerializer):
    product_title = serializers.CharField(source="product.title", read_only=True)

    class Meta:
        model = OrderItem
        fields = ["id", "product", "product_title", "quantity", "price"]


class PaymentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Payment
        fields = ["payment_id", "paid", "created_at"]


class OrderSerializer(serializers.ModelSerializer):
    items = OrderItemSerializer(many=True, read_only=True)
    payment = PaymentSerializer(read_only=True)
    invoice_url = serializers.SerializerMethodField()
    class Meta:
        model = Order
        fields = [
            "id",
            "user",
            "total_amount",
            "status",
            "buyer_name",
            "email",
            "invoice_pdf",
            "invoice_url",
            "created_at",
            "items",
            "payment"
        ]
    def get_invoice_url(self, obj):

        if obj.invoice_pdf:
            return obj.invoice_pdf.url

        return None
		




# orders/services.py
from django.db import transaction
from rest_framework.exceptions import ValidationError
from decimal import Decimal

from .models import Order, OrderItem, Payment
from books.models import Book


@transaction.atomic
def create_order_from_cart(user, cart_items, buyer_name, email):
    if not cart_items:
        raise ValidationError({"cart": "Cart is empty"})

    total_amount = Decimal("0.00")

    validated_items = []

    # =========================
    # 🧮 CALCULATE TOTAL FIRST
    # =========================
    for item in cart_items:
        book_id = item.get("id")
        quantity = item.get("quantity", 1)

        if quantity <= 0:
            raise ValidationError({"quantity": "Must be greater than 0"})

        try:
            book = Book.objects.get(id=book_id, is_active=True)
        except Book.DoesNotExist:
            raise ValidationError({"book": f"Book {book_id} not found"})

        price = Decimal(str(book.price))
        total_amount += price * Decimal(quantity)

        validated_items.append({
            "book": book,
            "quantity": quantity,
            "price": price
        })

    # =========================
    # ✅ CREATE ORDER WITH TOTAL
    # =========================
    order = Order.objects.create(
        user=user,
        buyer_name=buyer_name,
        email=email,
        status="PENDING",
        total_amount=total_amount
    )

    # =========================
    # 📦 CREATE ORDER ITEMS
    # =========================
    for item in validated_items:
        OrderItem.objects.create(
            order=order,
            product=item["book"],
            quantity=item["quantity"],
            price=item["price"]
        )

    # =========================
    # 💳 CREATE PAYMENT
    # =========================
    Payment.objects.create(
        order=order,
        payment_id="FREE_PAYMENT",
        paid=False
    )

    return order
	
# orders/tasks.py
from celery import shared_task
import logging
import os

from django.core.files import File
from django.conf import settings
from django.template import Template, Context

from weasyprint import HTML

from .models import Order

logger = logging.getLogger('orders')


@shared_task
def generate_invoice_pdf(order_id):

    order = Order.objects.get(id=order_id)

    invoice_dir = os.path.join(settings.MEDIA_ROOT, "invoices")
    os.makedirs(invoice_dir, exist_ok=True)

    filename = f"invoice_{order.id}.pdf"
    file_path = os.path.join(invoice_dir, filename)

    # =========================
    # INLINE HTML TEMPLATE (NO FILE NEEDED)
    # =========================
    html_template = """
    <html>
    <head>
        <style>
            body {
                font-family: Arial;
                padding: 30px;
                color: #333;
            }

            .header {
                text-align: center;
                margin-bottom: 20px;
            }

            .header h1 {
                margin: 0;
                font-size: 24px;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            table, th, td {
                border: 1px solid #ddd;
            }

            th, td {
                padding: 10px;
                text-align: left;
            }

            th {
                background: #f4f4f4;
            }

            .total {
                text-align: right;
                margin-top: 20px;
                font-size: 18px;
                font-weight: bold;
            }

            .footer {
                margin-top: 40px;
                text-align: center;
                font-size: 13px;
            }
        </style>
    </head>

    <body>

    <div class="header">
        <h1>SIYARAM BOOK STORE</h1>
        <p>Invoice / Tax Invoice</p>
    </div>

    <p><strong>Invoice No:</strong> INV-{{ order.id }}</p>
    <p><strong>Order ID:</strong> {{ order.id }}</p>
    <p><strong>Customer:</strong> {{ order.buyer_name }}</p>
    <p><strong>Email:</strong> {{ order.email }}</p>

    <table>
        <tr>
            <th>Item</th>
            <th>Qty</th>
            <th>Price</th>
            <th>Total</th>
        </tr>

        {% for item in items %}
        <tr>
            <td>{{ item.product.title }}</td>
            <td>{{ item.quantity }}</td>
            <td>₹{{ item.price }}</td>
            <td>₹{{ item.quantity }} x {{ item.price }}</td>
        </tr>
        {% endfor %}
    </table>

    <div class="total">
        Grand Total: ₹{{ grand_total }}
    </div>

    <div class="footer">
        Payment Status: {{ order.status }} <br>
        Thank you for shopping with Siyaram Book Store!
    </div>

    </body>
    </html>
    """

    # =========================
    # DATA PREPARATION
    # =========================
    items = order.items.all()

    grand_total = sum(item.quantity * item.price for item in items)

    context = Context({
        "order": order,
        "items": items,
        "grand_total": grand_total
    })

    template = Template(html_template)
    html_string = template.render(context)

    # =========================
    # GENERATE PDF
    # =========================
    HTML(string=html_string).write_pdf(file_path)

    # =========================
    # SAVE TO MODEL FIELD
    # =========================
    with open(file_path, "rb") as pdf_file:
        order.invoice_pdf.save(
            filename,
            File(pdf_file),
            save=True
        )

    return f"Invoice generated for order {order.id}"
	
	
# orders/utils.py
from contextlib import contextmanager  # Context managers
import asyncio  # Async IO
from functools import lru_cache  # LRU cache
from django.db.models import Count, F, Window  # Advanced queries
from django.db.models.functions import RowNumber  # Window function
from .models import Order
import copy
# Shallow vs deep copy demo
def copy_order_example(order):
    shallow = copy.copy(order)  # Shallow copy
    deep = copy.deepcopy(order)  # Deep copy
    return shallow, deep

# Custom exception
class OrderException(Exception):  # For order-specific errors
    pass

# Context manager demo
@contextmanager
def open_file_demo(file_path, mode="w"):
    f = open(file_path, mode)  # Open file
    try:
        yield f  # Yield file object
    finally:
        f.close()  # Close safely

# Decorator & closure demo
def log_decorator(func):
    def wrapper(*args, **kwargs):
        print(f"[LOG] Calling {func.__name__}")  # Pre-call log
        result = func(*args, **kwargs)  # Call original function
        print(f"[LOG] Finished {func.__name__}")  # Post-call log
        return result
    return wrapper

# Generator demo
def order_generator(order_list):
    for order in order_list:
        yield order  # Yield each order

# Async function demo
async def async_order_process(order):
    print(f"Processing order #{order.id} asynchronously...")
    await asyncio.sleep(1)  # Simulate async IO
    print(f"Order #{order.id} processed!")

# LRU cache demo
@lru_cache(maxsize=128)
def get_order_by_id(order_id):
    try:
        return Order.objects.get(id=order_id)  # Fetch from DB
    except Order.DoesNotExist:
        return None  # Return None if missing

# Advanced queryset examples
def user_order_counts():
    return Order.objects.values('user__username').annotate(total_orders=Count('id')).order_by('-total_orders')  # Group By

def order_ranking():
    return Order.objects.annotate(rank=Window(expression=RowNumber(), partition_by=[F('user')], order_by=F('quantity').desc()))  # Window function

def orders_with_optional_completed():
    return Order.objects.filter(completed__isnull=False)  # Filter NULL


# orders/views.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404

from core.responses import success_response, error_response
from users.models import UserEvent
from .models import Order, Payment
from .serializers import OrderSerializer, PaymentSerializer
from .services import create_order_from_cart
from .tasks import generate_invoice_pdf

class OrderViewSet(viewsets.ModelViewSet):
    serializer_class = OrderSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return Order.objects.all().order_by("-created_at")
        return Order.objects.filter(user=user).order_by("-created_at")


class PaymentViewSet(viewsets.ModelViewSet):
    serializer_class = PaymentSerializer
    permission_classes = [IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.is_staff:
            return Payment.objects.all().order_by("-created_at")
        return Payment.objects.filter(order__user=user).order_by("-created_at")


class MyOrdersAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        orders = Order.objects.filter(user=request.user).order_by("-created_at")
        serializer = OrderSerializer(orders, many=True)
        return success_response("Orders fetched", serializer.data)


class CreateFreeCartOrderAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        try:
            order = create_order_from_cart(
                user=request.user,
                cart_items=request.data.get("items", []),
                buyer_name=request.data.get("name"),
                email=request.data.get("email"),
            )

            return success_response(
                "Order created successfully",
                {
                    "order_id": order.id,
                    "total_amount": order.total_amount,
                }
            )

        except Exception as e:
            return error_response("Order creation failed", str(e))


class ConfirmPaymentAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, order_id):
        order = get_object_or_404(Order, id=order_id, user=request.user)

        if order.status == "SUCCESS":
            return error_response("Order already completed")

        if not hasattr(order, "payment"):
            return error_response("Payment record not found")

        order.status = "SUCCESS"
        order.save()

        order.payment.paid = True
        order.payment.save()
        generate_invoice_pdf.delay(order.id)
        UserEvent.objects.create(
            user=request.user,
            event_type="purchase",
            metadata={
                "order_id": order.id,
                "amount": str(order.total_amount),
            }
        )

        return success_response("Payment confirmed")
		
		
		
# orders/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    OrderViewSet,
    PaymentViewSet,
    MyOrdersAPIView,
    CreateFreeCartOrderAPIView,
    ConfirmPaymentAPIView,
)

router = DefaultRouter()
router.register(r"orders", OrderViewSet, basename="orders")
router.register(r"payments", PaymentViewSet, basename="payments")

urlpatterns = [
    # ViewSets
    path("", include(router.urls)),

    # Custom APIs
    path("my-orders/", MyOrdersAPIView.as_view(), name="my-orders"),
    path("create-order/", CreateFreeCartOrderAPIView.as_view(), name="create-order"),
    path("confirm-payment/<int:order_id>/", ConfirmPaymentAPIView.as_view(), name="confirm-payment"),
]