USE DATABASE BOOKSTORE_DW;

-- Bronze layer (ingestion)
CREATE SCHEMA IF NOT EXISTS RAW;

-- Silver layer (clean + transform)
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS INTERMEDIATE;

-- Gold layer (final analytics)
CREATE SCHEMA IF NOT EXISTS MARTS;

CREATE SCHEMA IF NOT EXISTS SNAPSHOTS;