
"""
Django settings for siyaram_bookstore project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost"
).split(",")


# Application definition

# Installed apps
INSTALLED_APPS = [
    "django.contrib.admin",  # Admin panel
    "django.contrib.auth",  # Authentication system
    "django.contrib.contenttypes",  # Generic relations support
    "django.contrib.sessions",  # Session management
    "django.contrib.messages",  # Flash messages
    "django.contrib.staticfiles",  # Static files handling
    "rest_framework",  # DRF APIs
    "rest_framework_simplejwt",  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # Blacklist support for JWT
    "django_filters",  # Filtering support
    "drf_yasg",  # Swagger docs
    "corsheaders",  # CORS handling (Security)
    "users",  # Custom users app
    "books",  # Books app
    "orders",  # Orders app
]

AUTH_USER_MODEL = "users.User"  # Custom user model
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Authorization: Bearer <access_token>"
        }
    },
    "USE_SESSION_AUTH": False,
}
# DRF configuration
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT auth
    ),
   "DEFAULT_PERMISSION_CLASSES": (
     "rest_framework.permissions.IsAuthenticated",   # Allow login/signup
    ),
    # "DEFAULT_THROTTLE_CLASSES": [
    #     "rest_framework.throttling.UserRateThrottle",  # Auth user limit
    #     "rest_framework.throttling.AnonRateThrottle",  # Anonymous limit
    # ],
    "DEFAULT_THROTTLE_RATES": {"user": "100/day", "anon": "10/day"},  # Throttle rates
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",  # Filter support
        "rest_framework.filters.SearchFilter",  # Search
        "rest_framework.filters.OrderingFilter",  # Ordering
    ),
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler",  # Custom error handler
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",  # Pagination
    "PAGE_SIZE": 10,  # Items per page
}

# JWT configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),  # Token expiry
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),  # Refresh token expiry
    "ROTATE_REFRESH_TOKENS": True,  # Rotate refresh tokens
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Middleware stack
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',  # Security headers
    'django.contrib.sessions.middleware.SessionMiddleware',  # Session middleware
    'django.middleware.common.CommonMiddleware',  # Common utilities
    'django.middleware.csrf.CsrfViewMiddleware',  # CSRF protection
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Attach user to request
    'django.contrib.messages.middleware.MessageMiddleware',  # Flash messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Clickjacking protection
]
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173"
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173"
).split(",")
# Optional: allow all during dev
CORS_ALLOW_ALL_ORIGINS = False
# Cache config using Redis
# Cache config using Redis when available
REDIS_URL = os.getenv("REDIS_URL")

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    # Fallback cache when Redis is not configured
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "siyaram-bookstore-cache",
        }
    }


# Celery configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

# RAZORPAY_KEY = os.getenv("RAZORPAY_KEY")
# RAZORPAY_SECRET = os.getenv("RAZORPAY_SECRET")
# RAZORPAY_WEBHOOK_SECRET = os.getenv("RAZORPAY_WEBHOOK_SECRET")

# Logging configuration
# LOGGING = {
#     'version': 1,  # Logging schema version
#     'disable_existing_loggers': False,  # Keep default loggers
#     'formatters': {'verbose': {'format': '[{levelname}] {asctime} {name} {message}', 'style': '{'}},  # Verbose format
#     'handlers': {'file': {'level': 'INFO', 'class': 'logging.FileHandler', 'filename': BASE_DIR / 'bookstore.log', 'formatter': 'verbose'}},  # File handler
#     'loggers': {
#         'django': {'handlers': ['file'], 'level': 'INFO', 'propagate': True},  # Django logger
#         'orders': {'handlers': ['file'], 'level': 'INFO', 'propagate': False},  # Orders logger
#     },
# }


DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ROOT_URLCONF = 'siyaram_bookstore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'siyaram_bookstore.wsgi.application'
ASGI_APPLICATION = 'siyaram_bookstore.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": os.getenv("POSTGRES_USER"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"