# Generated by Django 6.0.3 on 2026-04-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
    ]
